### ISSUE TITLE
Added Sysmon for Linux to relationships

### ISSUE THREAD

**Issue by Cyb3rWard0g** [OTRF/OSSEM-DM#36]
https://github.com/OTRF/OSSEM-DM/tree/main/relationships

Example:

```
name: Process created File
contributors:
- Jose Rodriguez @Cyb3rPandaH
- Roberto Rodriguez @Cyb3rWard0g
- Olaf Hartong @olafhartong
attack:
  data_source: File
  data_component: file creation
behavior:
  source: process
  relationship: created
  target: file
security_events:
- event_id: 11
  name: FileCreate.
  platform: Windows
  audit_category: FileCreate
  log_channel: Microsoft-Windows-Sysmon/Operational
  log_provider: Microsoft-Windows-Sysmon
- event_id: 11
  name: FileCreate.
  platform: Linux
  audit_category: FileCreate
  log_channel: Linux-Sysmon/Operational
  log_provider: Linux-Sysmon
- event_id: FileCreated
  name: FileCreated
  platform: Windows
  audit_category: null
  log_channel: DeviceFileEvents
  log_provider: Microsoft Defender for Endpoint
references:
notes:
```
